### ISSUE TITLE
"How to configure IntelliJ to enjoy Juzu development" Link cannot be viewed

### ISSUE THREAD

**Issue by alexpdh** [juzu/portlet-tutorial#3]
"How to configure IntelliJ to enjoy Juzu development" Link cannot be viewed

[https://community.exoplatform.com/portal/intranet/wiki/group/spaces/juzu/IntelliJ](https://community.exoplatform.com/portal/intranet/wiki/group/spaces/juzu/IntelliJ)

**Comment by fdrouet** [comment]
you just need to create an account on https://community.exoplatform.com/ to have access ;-)

**Comment by alexpdh** [comment]
Thanks!
